### ISSUE TITLE
bootstrap: use GitLab repos for `mesa-demos` and `xorg-xinit`

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [Andy-Python-Programmer/aero#103]
GitHub mirrors of `mesa-demos` and `xorg-xinit` from the [freedesktop](https://github.com/freedesktop/) GitHub have been moved to [GitLab](https://gitlab.freedesktop.org).

**Comment by shamb0** [comment]
Greetings, @Andy-Python-Programmer! As a newcomer to Aero, I aim to begin working on the platform by undertaking this Good First Issue. May I work with you on this task?

**Comment by Andy-Python-Programmer** [comment]
Yep, though there *may* be conflicts in one of the patches that you may need to resolve.

**Comment by shamb0** [comment]
Thanks @jwpjrdev, @Andy-Python-Programmer. I will proceed in a guided direction.

**Comment by Andy-Python-Programmer** [comment]
Hey @shamb0, would you still like to work on this issue?

**Comment by shamb0** [comment]
@Andy-Python-Programmer,

I apologize for the delay. I have been blocked on some other tasks.

Here are my updates:

- I was unable to build the userland sysroot (./aero.py --sysroot) on Ubuntu due to package dependency conflicts.
- I tried to build on Arch Linux using Docker, but I was blocked by the SDD image size limitations.

I will not be able to proceed with this task in the next few weeks. I would appreciate it if you could take over.
